if(bone1[1].x<battle_board.x-battle_board.left){
bone1[1].hspeed=2	
}else
if(bone1[1].x>battle_board.x+battle_board.right){
bone1[1].hspeed=-2	
}
if(bone1[2].x<battle_board.x-battle_board.left){
bone1[2].hspeed=2	
}else
if(bone1[2].x>battle_board.x+battle_board.right){
bone1[2].hspeed=-2	
}
alarm[1]=1