start=0
time=0
timer=0
lightproc1=0
lightproc2=0
gbstate=0
lightning=false
phase=0
zapspeed=5
zapspeedmax=120
_on=false
//instance_create_depth(battle_board.x,battle_board.y+battle_board.down,0,battle_bullet_simple_lightning)