//if(debug_mode){
	draw_set_font(font_mars_needs_cunnilingus)
	draw_set_color(c_white)
	draw_text(0,20,string(turn))
	draw_text(0,40,string(x))
	draw_text(0,60,string(y))
	draw_text(0,80,string(global.ballHit))
	draw_text(0,280,string(camera.x))
	draw_text(0,300,string(camera.y))
	/*draw_text(0,20,string(x))
	draw_text(0,40,string(y))
	draw_text(0,60,"test")
//}