if(_lemon_triggered=true){
	_lemon_dir+=_lemon_rotate
	repeat(7){
	_lemon[_lemon_proc2].x=self.x+lengthdir_x(_lemon_distance,_lemon_dir+(360/7)*_lemon_proc2)
	_lemon[_lemon_proc2].y=self.y-60+lengthdir_y(_lemon_distance,_lemon_dir+(360/7)*_lemon_proc2)
	_lemon_proc2++
	}
	if(_lemon_proc2>6){
	_lemon_proc2=0
	}
}